review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bloggers, only: [:new,:create,:index, :show]
  resources :destinations, only: [:new,:create,:index, :show]
  resources :posts, only: [:new,:create, :show, :edit, :update]
  get 'posts/:id/likes', to: 'posts#likes', as: 'post_likes'
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/models/blogger.rb
class Blogger < ApplicationRecord
    has_many :posts
    has_many :destinations, through: :posts

    validates :age, :numericality => {:greater_than => 0 }
    validates :name, uniqueness: true
    validates :bio, length: { minimum: 30 }

end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/models/destination.rb
class Destination < ApplicationRecord
    has_many :posts
    has_many :bloggers, through: :posts
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :blogger 
    belongs_to :destination 
    validates :title, presence: true
    validates :content, length: { minimum: 100 }
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
    def index
        @bloggers = Blogger.all
    end 

    def show
        @blogger = Blogger.find(params[:id])
    end 

    def new
        @blogger = Blogger.new
    end 

    def create
        @blogger = Blogger.create(blogger_params)
        if @blogger.valid?
            redirect_to blogger_path(@blogger)
        else
            flash[:errors] = @blogger.errors.full_messages
            redirect_to new_blogger_path
        end 
        # redirect_to @blogger
    end 

    private 

    def blogger_params
        params.require(:blogger).permit(:name, :age, :bio)
    end 
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/controllers/posts_controller.rb
class PostsController < ApplicationController    

def index
    @posts = Post.all
end 

def show
    @post = Post.find(params[:id])
end 

def new
    @post = Post.new
    @bloggers = Blogger.all
    @destinations = Destination.all
end 

def create
    @post = Post.create(post_params)
    if @post.valid?
        redirect_to post_path(@post)
    else
        flash[:errors] = @post.errors.full_messages
        redirect_to new_post_path
    end 
    # redirect_to @post
end 

def edit
    @post = Post.find(params[:id])
    @bloggers = Blogger.all
    @destinations = Destination.all
end 

def update
    @post = Post.find(params[:id])

    @post.update(post_params)
    
    if @post.valid?
        redirect_to post_path(@post)
    else
        flash[:errors] = @post.errors.full_messages
        redirect_to new_post_path
    end 
    

end 


def likes
    @post = Post.find(params[:id])
    @post.update(likes: @post.likes+=1)
    redirect_to post_path(@post)
end 

private 

def post_params
    params.require(:post).permit!
    #params.require(:post).permit(:title, :content, :likes, :blogger_id, :destination_id)
end 
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/helpers/bloggers_helper.rb
module BloggersHelper
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/helpers/destinations_helper.rb
module DestinationsHelper
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/helpers/posts_helper.rb
module PostsHelper
end

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelatr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/views/posts/_form.erb
<%= form_for @post do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.collection_select :blogger_id, @bloggers, :id, :name %>
    <%= f.collection_select :destination_id, @destinations, :id, :name %>
    <%= f.submit %>
<%end%>

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/views/posts/edit.html.erb
<%= render "form"%>

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/views/posts/new.html.erb
<%= render "form"%>

review/Rails-Practice-Code-Challenge-Travelatr-sfo01-seng-ft-082420/app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.content %></p>
<p><%= @post.likes %></p>
<button><%= link_to '<3', post_likes_path(@post) %></button>
<div><%= link_to @post.blogger.name, blogger_path(@post.blogger) %></div>
<div><%= @post.destination.name %></div>