18-Associations/candy/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources(:candy_stores, {only: [:index,:show]})

  resources :candy_stores
  resources :candy_items

  # get '/candy_stores', to: 'candy_stores#index'
  #method url, to: where it is going/what action it will hit
  get '/candy_stores/:id/toggle_open', to: 'candy_stores#toggle_open'
end

18-Associations/candy/app/models/candy_item.rb
class CandyItem < ApplicationRecord
  belongs_to :candy_store
end

18-Associations/candy/app/models/candy_store.rb
class CandyStore < ApplicationRecord
    has_many :candy_items
end

18-Associations/candy/app/controllers/candy_items_controller.rb
class CandyItemsController < ApplicationController
    before_action :get_candy_item, only: [:show, :edit, :update, :destroy]
   
    def index
        @candy_items = CandyItem.all
    end 

    def show
    end 

    def create 
        @candy_item = CandyItem.create(candy_params)
        redirect_to @candy_item
    end 

    def new
        @candy_item = CandyItem.new
        @candy_stores = CandyStore.all
    end 


    def edit
        @candy_stores = CandyStore.all
    end 
    
    def update
        @candy_item.update(candy_params)
        redirect_to candy_item_path(@candy_item)
    end 

    def destroy
        @candy_item.destroy()
        redirect_to candy_items_path

    end 

    private
    
    def get_candy_item
        @candy_item = CandyItem.find(params[:id])
    end

    def candy_params    
      params.require(:candy_item).permit(:name, :price,)
    end 


end

18-Associations/candy/app/controllers/candy_stores_controller.rb
class CandyStoresController < ApplicationController
    before_action :get_candy_store, only: [:show, :edit, :update, :destroy, :toggle_open]
    def index
        @candy_stores = CandyStore.all
    end 


    def new
        @candy_store = CandyStore.new()
    end 

    def create
        @candy_store = CandyStore.create(candy_params)
        redirect_to candy_store_path(@candy_store)
    end 

    def update
        @candy_store.update(candy_params)
        redirect_to candy_store_path(@candy_store)
    end 

    def destroy
        @candy_store.destroy
        redirect_to candy_stores_path
    end 

    def toggle_open
        @candy_store.update(open:!@candy_store.open)
        redirect_to candy_store_path(@candy_store)    
    end 


    private 

    def get_candy_store 
        @candy_store = CandyStore.find(params[:id]) 
    end 


    def candy_params
        params.require(:candy_store).permit(:name, :location)
    end 

end 

18-Associations/candy/app/views/candy_items/_form.erb
<%= form_for @candy_item do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%>
    <%= f.label :price%>
    <%= f.text_field :price%>
    <%= f.collection_select :candy_store_id, @candy_stores, :id, :name %>
    <%= f.submit %>
<% end %>

18-Associations/candy/app/views/candy_items/edit.erb
<%= render "form"%>

18-Associations/candy/app/views/candy_items/index.erb
<% @candy_items.each do |candy|%>
    <li><%= link_to candy.name, candy_item_path(candy)%>
<% end %>
<div>
<button> <%= link_to "New Candy", new_candy_item_path%> </button>
<button> <%= link_to "Candy Stores", candy_stores_path%> </button>
</div>

18-Associations/candy/app/views/candy_items/new.erb
<%= render "form"%>

18-Associations/candy/app/views/candy_items/show.erb
    <h1><%= @candy_item.name %></h1>
    <h1>Price: $<%= @candy_item.price %>.00</h1>
    <h1>Store: <%= @candy_item.candy_store.name%>

18-Associations/candy/app/views/candy_stores/edit.erb
 <%# <form action="candy_stores/<%=@candy_store.id%" method="POST">
    <input type="hidden" value="PATCH" name="_method">
    <label for="stoer-name">Store Name</label>
    <input type="text" name="name" />
    <label for="stoer-location">Store Location</label>
    <input type="text" name="location" />
    <input type="submit">
</form>
%>

<%#<%= form_tag "/candy_stores/#{@candy_store.id}", method:"PATCH" do%>
 <%#   <%= label_tag :name%>
 <%#   <%= text_field_tag :name, @candy_store.name %>
 <%#   <%= label_tag :location%>
 <%#   <%= text_field_tag :location, @candy_store.location %>
 <%#   <%= submit_tag%>
<%# <%end%>


<%= form_for @candy_store do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= f.submit %>
<%end%>

18-Associations/candy/app/views/candy_stores/index.erb
<h1>Candy Home!</h1>
<ul>
<% @candy_stores.each do |store| %>
<%# li> <%= link_to store.name, "candy_stores/#{store.id}"  %> </li>

<li> <%= link_to store.name, candy_store_path(store) %> </li>
<%end%>
</ul>
<button><%= link_to "New Store", new_candy_store_path%> </button>

18-Associations/candy/app/views/candy_stores/new.erb
<%= form_for @candy_store do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= f.submit%>
<%end%>

18-Associations/candy/app/views/candy_stores/show.erb
<h1><%= @candy_store.name%> </h1>
<h1><%= @candy_store.location%> </h1>
<h1><%= @candy_store.open == true ? "Open" : "Closed" %> </h1>
<%= link_to "Edit", edit_candy_store_path(@candy_store)%>
<%= button_to "DELETE", @candy_store, :method => :delete %>

18-Associations/candy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>