20-auth/trivia/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :responses

  resources :users, only: [:new, :create]
  resources :login, only: [:new, :create]

  get :'random-question', to: 'responses#new'
  delete "logout", to: "login#destroy", as: "log_out"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

20-auth/trivia/app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    has_many :responses
end

20-auth/trivia/app/models/question.rb
class Question < ApplicationRecord
    has_many :responses
    has_many :answers
    belongs_to :correct_answer, class_name: "Answer", optional: true

    def random_answers
        self.answers.order("RANDOM()")
    end
end

20-auth/trivia/app/models/response.rb
class Response < ApplicationRecord
    belongs_to :question
    belongs_to :answer
end

20-auth/trivia/app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :username
    validates_uniqueness_of :username
    
    has_secure_password

    # def password=(value)
    #     self.password_digest = BCrypt::Password.create(value)
    # end 

    # def authenticate(password)
        
    #     BCrypt::Password.new(self.password_digest) == password
    # end 



end

20-auth/trivia/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

20-auth/trivia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    def fetch_user
        byebug
        @logged_in = logged_in?
        if @logged_in
            @user = User.find(session[:user_id])
        else
            redirect_to new_login_path
        end 
    end 

    def logged_in?
        !!session[:user_id]
    end 

    def log_out_user!
        session.delete(:user_id)
    end 
end

20-auth/trivia/app/controllers/login_controller.rb
class LoginController < ApplicationController
# or SessionController
    skip_before_action :fetch_user, only:[:new, :create]
    def new
        @user = User.new
    end 

    def create
        @user = User.find_by(username:params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
         redirect_to new_response_path
        else
            redirect_to new_login_path
        end   
    end 

    def destroy
        log_out_user!
        redirect_to new_login_path
    end 

end

20-auth/trivia/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

20-auth/trivia/app/controllers/responses_controller.rb
      
class ResponsesController < ApplicationController

    before_action :define_question, :define_response

    def new

    end

    def define_question
        @question = Question.order("RANDOM()").limit(1)[0]
    end

    def define_response
        @questionResponse = Response.new({ question: @question })
    end

    def create
        
        #headers
        # @number_correct = 0
        
        cookies["number_correct"] ||= 0
        response = Response.create(response_params)
        #/responses/new
        if response.question.correct_answer == response.answer
            
            cookies["number_correct"] = cookies["number_correct"].to_i + 1
            flash["message"] ="Correct"
        else
            flash["message"] ="Incorrect"
        end
        redirect_to '/random-question'
    end

    def response_params
        params.require(:response).permit(:answer_id, :question_id)
    end

end

20-auth/trivia/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :fetch_user, only:[:new, :create]

    def new
        @user = User.new
    end 

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to new_response_path
        else 
            redirect_to new_user_path
        end
    end 
    private 

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

20-auth/trivia/app/helpers/answers_helper.rb
module AnswersHelper
end

20-auth/trivia/app/helpers/application_helper.rb
module ApplicationHelper
end

20-auth/trivia/app/helpers/questions_helper.rb
module QuestionsHelper
end

20-auth/trivia/app/helpers/responses_helper.rb
module ResponsesHelper
end

20-auth/trivia/app/helpers/users_helper.rb
module UsersHelper
end

20-auth/trivia/app/views/login/new.erb
<h1>Log in</h1>
<%= form_tag login_index_path, class: "auth-form" do %>
   <ul>
    <li>
      <%= label_tag :username %>
      <%= text_field_tag :username %>
    </li>
    <li>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </li>
  </ul>
  <%= submit_tag "Log in" %>
<% end %>

20-auth/trivia/app/views/responses/new.erb
<h3>Correct So Far: <%= @user.correct_answers %></h3>

<h1><%= @question.content %></h1>
<ul>
<%= form_with model:@questionResponse do | form | %>
    <%= form.hidden_field :question_id %>
    <label>Choices:</label>
    <% @question.random_answers.each do | answer | %>
        <div>
            <label><%= answer.content %></label>
            <%= form.radio_button :answer_id, answer.id%>
        </div>
    <% end %>
    <%= form.submit "Submit"%>
<% end %>
</ul>

<% if flash["message"] %>
  <p style="color:red">  <%= flash["message"]%> </p>
<%end%>

20-auth/trivia/app/views/users/new.erb
<h1>New User</h1>
<%= form_for @user do |f| %>
  <ul>
    <li>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
  </ul>
  <%= f.submit %>
<% end %>